apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3