apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
  replicas: 3
  selector:
    matchLabels:
      app: kubia